import { OAuth2Client, CodeChallengeMethod } from 'google-auth-library';
import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma';
import { env } from '../config/env';
import { AppError } from '../utils/AppError';
import { normalizeEmail } from '../utils/email';
import { issueTokenPair, type TokenPair } from './token.service';
import { toPublicUser, type PublicUser } from '../utils/publicUser';

function buildOAuthClient(): OAuth2Client {
  return new OAuth2Client(
    env.GOOGLE_CLIENT_ID,
    env.GOOGLE_CLIENT_SECRET,
    env.GOOGLE_REDIRECT_URI,
  );
}

/**
 * URL to send the browser to in order to start the Google consent flow.
 *
 * `nonce` and `codeChallenge` (PKCE, RFC 7636) are both generated by the
 * caller (auth.controller.ts) alongside `state` and stashed in the same
 * signed cookie, so they can be checked/replayed back on the matching
 * `code_verifier`/nonce parameters below once the callback comes in.
 * `code_challenge_method: 'S256'` (never `'plain'`) is what actually makes
 * PKCE meaningful — Google recomputes SHA-256(code_verifier) at token-exchange
 * time and rejects the exchange if it doesn't match this challenge, closing
 * the "authorization code interception" gap: even if the one-time `code`
 * itself leaked (a referrer header, a proxy log, a malicious app on the same
 * device intercepting the redirect), it's useless without the verifier that
 * only this backend ever held.
 */
export function getGoogleAuthUrl(state: string, nonce: string, codeChallenge: string): string {
  const client = buildOAuthClient();
  return client.generateAuthUrl({
    access_type: 'online',
    scope: ['openid', 'email', 'profile'],
    prompt: 'consent',
    state,
    nonce,
    code_challenge: codeChallenge,
    code_challenge_method: CodeChallengeMethod.S256,
  });
}

interface GoogleProfile {
  googleId: string;
  email: string;
  emailVerified: boolean;
  name: string | null;
}

/**
 * Exchanges the authorization `code` from Google's callback for the user's
 * verified profile.
 *
 * `codeVerifier` is the PKCE secret generated alongside `state`/`nonce` at
 * the start of this flow (auth.controller.ts) and never sent to the browser
 * separately from the signed cookie it's held in — passing it here is what
 * proves this exchange is happening from the same place that started the
 * flow, per RFC 7636.
 *
 * `expectedNonce` is compared against the `nonce` claim Google embeds in the
 * signed ID token. `verifyIdToken` below only proves Google issued this
 * specific token for our client ID and that it hasn't expired/been
 * tampered with — it says nothing about whether it's the token for *this*
 * sign-in attempt. Without the nonce check, a token obtained via some other
 * means (e.g. a different, concurrently-running OAuth flow, or one an
 * attacker otherwise got Google to issue) but still validly signed for this
 * client ID could be replayed into this callback.
 */
export async function exchangeCodeForProfile(
  code: string,
  codeVerifier: string,
  expectedNonce: string,
): Promise<GoogleProfile> {
  const client = buildOAuthClient();

  let idToken: string | undefined | null;
  try {
    const { tokens } = await client.getToken({ code, codeVerifier });
    idToken = tokens.id_token;
  } catch {
    throw new AppError(400, 'Failed to exchange Google authorization code');
  }

  if (!idToken) {
    throw new AppError(400, 'Google did not return an ID token');
  }

  const ticket = await client.verifyIdToken({
    idToken,
    audience: env.GOOGLE_CLIENT_ID,
  });
  const payload = ticket.getPayload();
  if (!payload?.sub || !payload.email) {
    throw new AppError(400, 'Google ID token is missing required claims');
  }
  if (payload.nonce !== expectedNonce) {
    throw new AppError(400, 'Google ID token nonce mismatch');
  }

  return {
    googleId: payload.sub,
    // Reuses the exact same normalization signup/login use (src/utils/email.ts)
    // rather than reimplementing trim+lowercase here — two independent
    // "canonical email" implementations drifting apart is exactly what would
    // make the email-based account-linking lookup below miss a real match.
    email: normalizeEmail(payload.email),
    emailVerified: payload.email_verified ?? false,
    name: payload.name ?? null,
  };
}

/**
 * Finds the local user matching a Google profile, creating or linking one as
 * needed:
 *  - already linked to this Google account -> return it
 *  - an account with this email exists (e.g. signed up with a password) AND
 *    that account has already independently proven ownership of the email
 *    (isEmailVerified) -> link it, but only then — see the comment below
 *  - otherwise -> create a brand-new, password-less account
 *
 * A single query checks both `googleId` and `email` (rather than two
 * sequential round trips) since at most one of them can realistically match
 * under normal operation — both columns are unique, and a user's googleId is
 * only ever set together with (or onto) the row for their one email.
 */
export async function findOrCreateGoogleUser(profile: GoogleProfile) {
  const existing = await prisma.user.findFirst({
    where: { OR: [{ googleId: profile.googleId }, { email: profile.email }] },
  });

  if (existing?.googleId === profile.googleId) {
    return existing;
  }

  if (existing) {
    if (!profile.emailVerified) {
      throw new AppError(400, 'Google account email is not verified');
    }
    if (!existing.isEmailVerified) {
      // The account-takeover fix: `profile.emailVerified` only says GOOGLE
      // has verified this email — it says nothing about whether THIS
      // existing row ever did. auth.service.ts's signup() never required
      // proof of email ownership for a password account, so without this
      // check an attacker could sign up first with someone else's email
      // (no verification needed), and the real owner's later, genuinely
      // Google-verified sign-in would silently link onto — and leave
      // standing, working password access on — the attacker's account.
      // This is the "classic-federated merge" pre-account-hijacking
      // pattern (Paverd et al., USENIX Security 2022).
      //
      // Refuse the silent link. The user has to prove they hold the
      // EXISTING account first — either verifying its email
      // (POST /auth/email/verify/*) or resetting its password
      // (POST /auth/password/reset/*, which also marks the email verified
      // and revokes every outstanding session on the account — see
      // auth.service.ts's confirmPasswordReset) — after which this exact
      // Google sign-in links cleanly on the next attempt.
      throw new AppError(
        409,
        'An account with this email already exists but has not verified ownership of it. ' +
          'Verify your email or reset your password first, then sign in with Google again.',
      );
    }
    try {
      return await prisma.user.update({
        where: { id: existing.id },
        data: { googleId: profile.googleId },
      });
    } catch (err) {
      if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
        // `googleId` is @unique, and this update is racing whatever else
        // might be claiming it concurrently — most plausibly the same
        // login double-firing (a double-click, two tabs), in which case
        // some other in-flight request already set this exact googleId on
        // this exact row, and re-reading it is the correct outcome, not a
        // failure. But it's also possible (correctly) rejected: this
        // googleId already belongs to a genuinely DIFFERENT user account —
        // that's a real conflict, not a race, and must not be silently
        // papered over by handing back the wrong user.
        const winner = await prisma.user.findUnique({ where: { googleId: profile.googleId } });
        if (winner && winner.email === existing.email) {
          return winner;
        }
        throw new AppError(409, 'This Google account is already linked to a different user');
      }
      throw err;
    }
  }

  // Same TOCTOU shape as auth.service.ts's signup() (see EXPLANATION.md §10):
  // the findFirst above is a fast-path check, not a guard — two Google
  // logins for the same brand-new account arriving close together (a
  // double-click on "Continue with Google", or two tabs) can both see "no
  // existing user" and both reach this create(). Only one INSERT can
  // actually win against the `email`/`googleId` unique constraints; without
  // this catch, the loser would throw a raw, unhandled
  // PrismaClientKnownRequestError straight into errorHandler's generic `500`
  // branch, on what is, from the user's perspective, a successful login.
  try {
    return await prisma.user.create({
      data: {
        email: profile.email,
        googleId: profile.googleId,
        name: profile.name,
        isEmailVerified: profile.emailVerified,
        passwordHash: null,
      },
    });
  } catch (err) {
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === 'P2002') {
      // Lost the race — the concurrent request that won it already created
      // (or linked) the row we were about to create. Fetch and return that
      // instead of failing a login that, functionally, just succeeded
      // via the other request.
      const winner = await prisma.user.findFirst({
        where: { OR: [{ googleId: profile.googleId }, { email: profile.email }] },
      });
      if (winner) {
        return winner;
      }
    }
    throw err;
  }
}

export interface GoogleLoginResult {
  user: PublicUser;
  tokens: TokenPair;
}

export async function loginWithGoogleCode(
  code: string,
  codeVerifier: string,
  expectedNonce: string,
): Promise<GoogleLoginResult> {
  const profile = await exchangeCodeForProfile(code, codeVerifier, expectedNonce);
  const user = await findOrCreateGoogleUser(profile);
  const tokens = await issueTokenPair(user);
  return { user: toPublicUser(user), tokens };
}
